/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPoojasRouteImport } from './routes/_app.poojas'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppNearbyRouteImport } from './routes/_app.nearby'
import { Route as AppHeatmapRouteImport } from './routes/_app.heatmap'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppTempleSlugRouteImport } from './routes/_app.temple.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPoojasRoute = AppPoojasRouteImport.update({
  id: '/poojas',
  path: '/poojas',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNearbyRoute = AppNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AppRoute,
} as any)
const AppHeatmapRoute = AppHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppTempleSlugRoute = AppTempleSlugRouteImport.update({
  id: '/temple/$slug',
  path: '/temple/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AppChatRoute
  '/heatmap': typeof AppHeatmapRoute
  '/nearby': typeof AppNearbyRoute
  '/notifications': typeof AppNotificationsRoute
  '/plan': typeof AppPlanRoute
  '/poojas': typeof AppPoojasRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/temple/$slug': typeof AppTempleSlugRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AppChatRoute
  '/heatmap': typeof AppHeatmapRoute
  '/nearby': typeof AppNearbyRoute
  '/notifications': typeof AppNotificationsRoute
  '/plan': typeof AppPlanRoute
  '/poojas': typeof AppPoojasRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/': typeof AppIndexRoute
  '/temple/$slug': typeof AppTempleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/heatmap': typeof AppHeatmapRoute
  '/_app/nearby': typeof AppNearbyRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/poojas': typeof AppPoojasRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/': typeof AppIndexRoute
  '/_app/temple/$slug': typeof AppTempleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/chat'
    | '/heatmap'
    | '/nearby'
    | '/notifications'
    | '/plan'
    | '/poojas'
    | '/profile'
    | '/search'
    | '/temple/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/chat'
    | '/heatmap'
    | '/nearby'
    | '/notifications'
    | '/plan'
    | '/poojas'
    | '/profile'
    | '/search'
    | '/'
    | '/temple/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/chat'
    | '/_app/heatmap'
    | '/_app/nearby'
    | '/_app/notifications'
    | '/_app/plan'
    | '/_app/poojas'
    | '/_app/profile'
    | '/_app/search'
    | '/_app/'
    | '/_app/temple/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/poojas': {
      id: '/_app/poojas'
      path: '/poojas'
      fullPath: '/poojas'
      preLoaderRoute: typeof AppPoojasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nearby': {
      id: '/_app/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AppNearbyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/heatmap': {
      id: '/_app/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof AppHeatmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/temple/$slug': {
      id: '/_app/temple/$slug'
      path: '/temple/$slug'
      fullPath: '/temple/$slug'
      preLoaderRoute: typeof AppTempleSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppHeatmapRoute: typeof AppHeatmapRoute
  AppNearbyRoute: typeof AppNearbyRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlanRoute: typeof AppPlanRoute
  AppPoojasRoute: typeof AppPoojasRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTempleSlugRoute: typeof AppTempleSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppHeatmapRoute: AppHeatmapRoute,
  AppNearbyRoute: AppNearbyRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlanRoute: AppPlanRoute,
  AppPoojasRoute: AppPoojasRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppTempleSlugRoute: AppTempleSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
